---
abstract: 'DBIC compat with Rose::DBx::Object::MoreHelpers'
author:
  - 'Peter Karman <karman@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.132510'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DBIx-Class-RDBOHelpers
no_index:
  directory:
    - t
    - inc
requires:
  DBICx::TestDatabase: 0
  DBIx::Class: 0
  Data::Dump: 0
  Test::More: 0
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=DBIx-Class-RDBOHelpers
  homepage: https://github.com/karpet/dbix-class-rdbohelpers
  license: http://dev.perl.org/licenses/
  repository: https://github.com/karpet/dbix-class-rdbohelpers
version: 0.11
